name: Composite java action
description: Setup JDK and maven
inputs:
  distribution:
    description: Which JDK to use
    default: temurin
  java-version:
    description: Major version of JDK
    required: true
  maven-version:
    description: Version of Maven to use
    required: true
    default: 3.8.2
  overwrite-settings:
    description: Overwrite settings.xml
    required: false
    default: false
  cache:
    description: Caching of artifacts
    required: false
    default: true

runs:
  using: "composite"
  steps:
  - name: Setup java
    uses: actions/setup-java@v2.2.0
    with:
      distribution: ${{ inputs.distribution }}
      overwrite-settings: ${{ inputs.overwrite-settings }}
      java-version: ${{ inputs.java-version }}

  - name: Set up Maven
    uses: stCarolas/setup-maven@v4.1
    with:
      maven-version: ${{ inputs.maven-version }}

  - name: Cache local Maven repository
    # https://github.com/actions/runner/issues/1283
    # if: inputs.cache
    uses: actions/cache@v2.1.6
    with:
      path: ~/.m2/repository
      key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      restore-keys: |
        ${{ runner.os }}-maven-
